(defpackage #:org.shirakumo.multiposter
  (:use #:cl)
  ;; protocol.lisp
  (:export
   #:add-tag
   #:post
   #:ready-p
   #:setup
   #:undo
   #:failed-p
   #:add-client
   #:add-profile
   #:find-profile
   #:find-client
   #:post
   #:title
   #:header
   #:footer
   #:description
   #:content-warning
   #:tags
   #:compose-post
   #:image-post
   #:files
   #:file-descriptions
   #:video-post
   #:file
   #:link-post
   #:url
   #:text-post
   #:client
   #:name
   #:post-tags
   #:define-client
   #:result
   #:client
   #:post-object
   #:url
   #:profile
   #:name
   #:clients
   #:tags
   #:header
   #:footer
   #:multiposter
   #:default-profile)
  ;; config.lisp
  (:export
   #:config-file
   #:load-config
   #:save-config)
  ;; toolkit.lisp
  (:export
   #:*image-types*
   #:*video-types*
   #:or*
   #:file-type-p
   #:envvar
   #:parse-tags
   #:merge-paragraphs
   #:initargs
   #:make-like
   #:alphanumeric-p
   #:non-space-p
   #:non-comma-p
   #:filter-tags
   #:trim-text
   #:compose-post-text
   #:query
   #:verbose
   #:timestamp
   #:path-url)
  ;; clients
  (:export
   #:dummy
   #:file
   #:git
   #:lichat
   #:mastodon
   #:studio
   #:tumblr))
